#NAME	"LingvoUniversal (En-Ru)"
#INDEX_LANGUAGE	"English"
#CONTENTS_LANGUAGE	"Russian"

quicken
	\[[t]'kwɪk(ə)n[/t]\] [p]брит.[/p] [s]quicken.wav[/s] / [p]амер.[/p] [s]10281.wav[/s]
	[b]I[/b] [p]гл.[/p]
	[m1]1)[/m]
	[m2]а) [trn]ускорять[/trn][/m]
	[m3][*][ex][lang id=1033]You'll have to quicken up your rate of work if you want to finish by the agreed date.[/lang] — Тебе нужно работать побыстрее, если ты хочешь закончить к сроку.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]He quickened his pace a little.[/lang] — Он слегка ускорил шаг.[/ex][/*][/m]
	[m3][*][b]Syn:[/b][/*][/m]
	[m3][*][ref]expedite[/ref] 1., [ref]precipitate[/ref] 3.[/*][/m]
	[m2]б) [trn]ускоряться[/trn][/m]
	[m3][*][ex][lang id=1033]His breath quickened.[/lang] — Его дыхание участилось.[/ex][/*][/m]
	[m2][*]••[/*][/m]
	[m2][*][b]Syn:[/b][/*][/m]
	[m2][*][ref]accelerate[/ref], [ref]hasten[/ref], [ref]hurry[/ref] 2., [ref]speed[/ref] 2.[/*][/m]
	[m2][*][b]Ant:[/b][/*][/m]
	[m2][*][ref]slow[/ref] 3.[/*][/m]
	[m1]2) [p][trn]книжн.[/trn][/p][/m]
	[m2]а) [trn]оживить, вдохнуть жизнь[/trn][/m]
	[m3][*][b]Syn:[/b][/*][/m]
	[m3][*][ref]animate[/ref] 2., [ref]enliven[/ref][/*][/m]
	[m2]б) [trn]ожить, обрести жизнь, стать живым[/trn][/m]
	[m3][*][ex][lang id=1033]The seed which is sown shall one day sprout and quicken.[/lang] — Посеянные семена однажды прорастут и оживут.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the hopes that quicken[/lang] — возрождающиеся надежды[/ex][/*][/m]
	[m2][*]••[/*][/m]
	[m2][*][b]Syn:[/b][/*][/m]
	[m2][*][ref]revive[/ref], [ref]vivify[/ref][/*][/m]
	[m1]3) [p][trn]книжн.[/p] возбуждать, побуждать, воодушевлять, стимулировать[/trn][/m]
	[m2][*][b]Syn:[/b][/*][/m]
	[m2][*][ref]stimulate[/ref], [ref]stir up[/ref], [ref]rouse[/ref] I, 1., [ref]excite[/ref], [ref]inspire[/ref][/*][/m]
	[m1]4)[/m]
	[m2]а) [trn]начинать чувствовать движение плода [i][com](при беременности)[/com][/trn][/i][/m]
	[m2]б) [trn]начинать двигаться [i][com](о плоде)[/com][/trn][/i][/m]
	[m1]5) [p][trn]уст.[/p] увеличивать кривизну [i][com](кривой)[/com][/i], крутизну [i][com](склона, скоса)[/com][/trn][/i][/m]
	[b]II[/b] [p]сущ.[/p][c];[/c] [p]бот.[/p]
	[m1][trn]рябина (обыкновенная); рябина домашняя[/trn][/m]
	[m2][*][b]Syn:[/b][/*][/m]
	[m2][*][ref]rowan-tree[/ref], [ref]service tree[/ref][/*][/m]
	
query
	\[[t]'kwɪərɪ[/t]\] [p]брит.[/p] [s]query.wav[/s] / [p]амер.[/p] [s]10273.wav[/s]
	[m1][b]1.[/b] [p]сущ.[/p][c];[/c] [p]книжн.[/p][/m]
	[m1]1) [trn]вопрос[/trn][/m]
	[m2][*][ex][lang id=1033]to raise a query about smth.[/lang] — задать вопрос о чём-л.[/ex][/*][/m]
	[m2][*][ex][lang id=1033]to answer a query[/lang] — отвечать на вопрос[/ex][/*][/m]
	[m2][*][ex][lang id=1033]We have a number of queries regarding delivery.[/lang] — У нас есть несколько вопросов по доставке.[/ex][/*][/m]
	[m2][*][b]Syn:[/b][/*][/m]
	[m2][*][ref]question[/ref] 1., [ref]inquiry[/ref][/*][/m]
	[m1]2) [p]информ.[/p] [trn]запрос[/trn][/m]
	[m1]3) [trn]сомнение[/trn][/m]
	[m2][*][ex][lang id=1033]There was a query as to who actually owned the hotel.[/lang] — Возникло сомнение относительно того, кто же на самом деле был хозяином отеля.[/ex][/*][/m]
	[m1]4) [trn]вопросительный знак [i][com](на полях текста)[/com][/trn][/i][/m]
	[m2][*][ex][lang id=1033]Put a query against Jack's name[/lang] — I'm not sure if he's coming. — Поставь вопросительный знак напротив имени Джека - я не уверен, что он придёт.[/ex][/*][/m]
	[m1][b]2.[/b] [p]гл.[/p][/m]
	[m1]1)[/m]
	[m2]а) [trn]спрашивать; осведомляться; выяснять, уточнять[/trn][/m]
	[m3][*][ex][lang id=1033]to query smb. about smb./ smth.[/lang] — расспрашивать кого-л. о ком-л. / чём-л.[/ex][/*][/m]
	[m2]б) [trn]консультироваться[/trn][/m]
	[m3][*][ex][lang id=1033]I must query your suggestion with the director, it doesn't seem completely suitable.[/lang] — Я должен проконсультироваться насчёт вашего предложения с директором - мне кажется, что оно не вполне приемлемо.[/ex][/*][/m]
	[m1]2) [trn]запрашивать [i][com](информацию)[/com][/trn][/i][/m]
	[m1]3) [trn]выражать сомнение, подвергать сомнению[/trn][/m]
	[m1]4) [trn]ставить вопросительный знак; помечать вопросительным знаком[/trn][/m]
quest
	\[[t]kwest[/t]\] [p]брит.[/p] [s]quest.wav[/s] / [p]амер.[/p] [s]10274.wav[/s]
	[m1][b]1.[/b] [p]сущ.[/p][c];[/c] [p]книжн.[/p][/m]
	[m1]1) [trn]поиск(и)[/trn][/m]
	[m2][*][ex][lang id=1033]in quest of smb. / smth.[/lang] — в поисках кого-л. / чего-л.[/ex][/*][/m]
	[m2][*][ex][lang id=1033]quest for oil[/lang] — поиск нефти[/ex][/*][/m]
	[m1]2) [p][trn]поэт.[/p] предмет поисков, искомый предмет[/trn][/m]
	[m1]3) [p]ист.[/p] [trn]поиски приключений [i][com](в рыцарских романах)[/com][/trn][/i][/m]
	[m1]4) [p]уст.[/p] [trn]сбор пожертвований [i][com](в римско-католической церкви)[/com][/trn][/i][/m]
	[m1][b]2.[/b] [p]гл.[/p][c];[/c] [p]книжн.[/p][/m]
	[m1]1) [i][trn][com](quest for)[/com][/i] искать; производить поиски, разыскивать[/trn][/m]
	[m2][*][ex][lang id=1033]For over 100 years, men have been questing for gold in the hills.[/lang] — Уже больше ста лет люди искали в этих холмах золото.[/ex][/*][/m]
	[m1]2)[/m]
	[m2]а) [p]охот.[/p] [trn]искать дичь [i][com](о собаках)[/com][/trn][/i][/m]
	[m2]б) [trn]искать пищу [i][com](о животных)[/com][/trn][/i][/m]
	[m1]3) [p]уст.[/p] [trn]собирать пожертвования [i][com](в католической церкви)[/com][/trn][/i][/m]
question
	\[[t]'kwesʧən[/t]\] [p]брит.[/p] [s]question.wav[/s] / [p]амер.[/p] [s]10275.wav[/s]
	[m1][b]1.[/b] [p]сущ.[/p][/m]
	[m1]1) [trn]вопрос[/trn][/m]
	[m2][*][ex][lang id=1033]awkward question[/lang] — неуместный, нелепый вопрос[/ex][/*][/m]
	[m2][*][ex][lang id=1033]blunt / direct question[/lang] — прямой вопрос[/ex][/*][/m]
	[m2][*][ex][lang id=1033]embarrassing question[/lang] — нескромный вопрос[/ex][/*][/m]
	[m2][*][ex][lang id=1033]examination question[/lang] — экзаменационный вопрос[/ex][/*][/m]
	[m2][*][ex][lang id=1033]hypothetical question[/lang] — гипотетический вопрос[/ex][/*][/m]
	[m2][*][ex][lang id=1033]indirect / oblique / reported question[/lang] — [p]лингв.[/p] косвенный вопрос[/ex][/*][/m]
	[m2][*][ex][lang id=1033]irrelevant question[/lang] — вопрос, не относящийся к делу; вопрос не по теме[/ex][/*][/m]
	[m2][*][ex][lang id=1033]pointed / tricky question[/lang] — каверзный вопрос[/ex][/*][/m]
	[m2][*][ex][lang id=1033]relevant question[/lang] — вопрос, относящийся к делу; вопрос по теме[/ex][/*][/m]
	[m2][*][ex][lang id=1033]rhetorical question[/lang] — риторический вопрос[/ex][/*][/m]
	[m2][*][ex][lang id=1033]to address / put a question to smb.[/lang] — задавать вопрос кому-л.[/ex][/*][/m]
	[m2][*][ex][lang id=1033]to answer / reply to / respond to a question[/lang] — отвечать на вопрос[/ex][/*][/m]
	[m2][*][ex][lang id=1033]to bring up / raise a question[/lang] — поднимать, ставить вопрос[/ex][/*][/m]
	[m2][*][ex][lang id=1033]to parry smb.'s question[/lang] — парировать чей-л. вопрос[/ex][/*][/m]
	[m2][*][ex][lang id=1033]The senator fielded all the questions.[/lang] — Сенатор ответил на все вопросы.[/ex][/*][/m]
	[m2][*]- [ref]academic question[/ref][/*][/m]
	[m2][*]- [ref]leading question[/ref][/*][/m]
	[m2][*]- [ref]loaded question[/ref][/*][/m]
	[m2][*]- [ref]million dollar question[/ref][/*][/m]
	[m2][*][b]Syn:[/b][/*][/m]
	[m2][*][ref]query[/ref] 1., [ref]inquiry[/ref][/*][/m]
	[m2][*][b]Gram:[/b][/*][/m]
	[m2][*]-QuestionQuestion markQuestions and negatives[/*][/m]
	[m1]2)[/m]
	[m2]а) [trn]проблема, дело; задача; обсуждаемый вопрос[/trn][/m]
	[m3][*][ex][lang id=1033]burning / explosive question[/lang] — животрепещущий, насущный вопрос[/ex][/*][/m]
	[m3][*][ex][lang id=1033]controversial / debatable / moot question[/lang] — спорный, дискуссионный вопрос[/ex][/*][/m]
	[m3][*][ex][lang id=1033]crucial question[/lang] — важный, ключевой вопрос[/ex][/*][/m]
	[m3][*][ex][lang id=1033]open question[/lang] — нерешённая проблема, открытый вопрос[/ex][/*][/m]
	[m3][*][ex][lang id=1033]sticky / thorny / ticklish / tricky question[/lang] — сложный, щекотливый вопрос[/ex][/*][/m]
	[m3][*][ex][lang id=1033]vexed question[/lang] — больной вопрос[/ex][/*][/m]
	[m3][*][ex][lang id=1033]statement of a question[/lang] — постановка вопроса[/ex][/*][/m]
	[m3][*][ex][lang id=1033]smth. in question[/lang] — что-л., о чём идёт речь[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the question is[/lang] — дело в том, что[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the matter in question[/lang] — рассматриваемый вопрос[/ex][/*][/m]
	[m3][*]- [ref]come into question[/ref][/*][/m]
	[m3][*]- [ref]go into the question[/ref][/*][/m]
	[m3][*][b]Syn:[/b][/*][/m]
	[m3][*][ref]problem[/ref] 1., [ref]matter[/ref] 1.[/*][/m]
	[m2]б) [p][trn]полит.[/p] предложение[/trn][/m]
	[m3][*]- [ref]put the question[/ref][/*][/m]
	[m1]3) [trn]сомнение; возражение[/trn][/m]
	[m2][*][ex][lang id=1033]beyond (all) / out of / past / without question[/lang] — без сомнения, вне всякого сомнения[/ex][/*][/m]
	[m2][*][ex][lang id=1033]It's true beyond question.[/lang] — Вне всякого сомнения, это правда.[/ex][/*][/m]
	[m2][*][ex][lang id=1033]to clear up a question[/lang] — разрешить сомнение[/ex][/*][/m]
	[m2][*][ex][lang id=1033]to make no question of smth.[/lang] — не сомневаться в чём-л., не подвергать что-л. сомнению[/ex][/*][/m]
	[m2][*][ex][lang id=1033]He requires from generals and officers that they carry out orders without questions.[/lang] — Он требует, чтобы генералы и офицеры исполняли приказы без обсуждения.[/ex][/*][/m]
	[m2][*]- [ref]call smth. in question[/ref][/*][/m]
	[m2][*][b]Syn:[/b][/*][/m]
	[m2][*][ref]objection[/ref][/*][/m]
	[m1]4) [trn]возможность, шанс[/trn][/m]
	[m2][*][ex][lang id=1033]There is no question of escape.[/lang] — Нет ни малейшего шанса сбежать.[/ex][/*][/m]
	[m2][*][b]Syn:[/b][/*][/m]
	[m2][*][ref]chance[/ref] 1., [ref]possibility[/ref][/*][/m]
	[m1]5)[/m]
	[m2]а) [trn]допрос, следствие; расследование[/trn][/m]
	[m2]б) [p][trn]ист.[/p] пытка[/trn][/m]
	[m3][*][ex][lang id=1033]to put smb. to the question[/lang] — подвергать пытке[/ex][/*][/m]
	[m1][*]•[/*][/m]
	[m1]- [ref]pop the question[/ref][/m]
	[m1][b]2.[/b] [p]гл.[/p][/m]
	[m1]1)[/m]
	[m2]а) [trn]спрашивать, задавать вопросы[/trn][/m]
	[m3][*][b]Syn:[/b][/*][/m]
	[m3][*][ref]ask[/ref], [ref]inquire[/ref][/*][/m]
	[m2]б) [trn]допрашивать; выпытывать, выспрашивать[/trn][/m]
	[m3][*][b]Syn:[/b][/*][/m]
	[m3][*][ref]interrogate[/ref], [ref]quiz[/ref] II, 2., [ref]examine[/ref][/*][/m]
	[m1]2) [trn]подвергать сомнению, сомневаться[/trn][/m]
	[m2][*][ex][lang id=1033]to question the credibility of smb.'s. story[/lang] — сомневаться в правдоподобности чьего-л. рассказа[/ex][/*][/m]
	[m2][*][ex][lang id=1033]to question the wisdom of smth.[/lang] — сомневаться в разумности чего-л.[/ex][/*][/m]
	[m2][*][b]Syn:[/b][/*][/m]
	[m2][*][ref]doubt[/ref] 1., [ref]dispute[/ref] 2.[/*][/m]
	[m1]3) [trn]исследовать; рассматривать [i][com](явления, факты)[/com][/trn][/i][/m]
	[m2][*][ex][lang id=1033]The professor wants us to question facts.[/lang] — Профессор хочет, чтобы мы рассмотрели факты.[/ex][/*][/m]
	[m2][*][b]Syn:[/b][/*][/m]
	[m2][*][ref]examine[/ref][/*][/m]
question from the floor
	[m1][trn]вопрос с места[/trn][/m]
question mark
	[m1][trn]знак вопроса, вопросительный знак[/trn][/m]

long
	\[[t]lɔŋ[/t]\] [p]брит.[/p] [s]long.wav[/s] / [p]амер.[/p] [s]7611.wav[/s]
	[b]I[/b]
	[m1][b]1.[/b] [p]прил.[/p][/m]
	[m1]1)[/m]
	[m2]а) [trn]длинный; больше своей ширины[/trn][/m]
	[m3][*][ex][lang id=1033]long legs / arms / fingernails[/lang] — длинные ноги, руки, ногти[/ex][/*][/m]
	[m3][*][ex][lang id=1033]long road / journey[/lang] — дальняя дорога[/ex][/*][/m]
	[m3][*][ex][lang id=1033]long distance[/lang] — дальнее расстояние[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the long side of the room[/lang] — длина комнаты[/ex][/*][/m]
	[m3][*][ex][lang id=1033]it's a long way to go[/lang] — это далеко[/ex][/*][/m]
	[m3][*][ex][lang id=1033]a long way about[/lang] — немалый крюк [i][com](объезд)[/com][/ex][/i][/*][/m]
	[m3][*][ex][lang id=1033]at long range[/lang] — на большом расстоянии[/ex][/*][/m]
	[m3][*][ex][lang id=1033]long waves[/lang] [p]радио[/p] — длинные волны[/ex][/*][/m]
	[m3][*][ex][lang id=1033]He came from a long way off.[/lang] — Прибыл он издалека.[/ex][/*][/m]
	[m3][*]- [ref]long measures[/ref][/*][/m]
	[m2]б) [p][trn]разг.[/p] долговязый, высокий[/trn][/m]
	[m3][*][b]Syn:[/b][/*][/m]
	[m3][*][ref]tall[/ref][/*][/m]
	[m2]в) [trn]обладающий определённой протяжённостью; имеющий такую-то длину[/trn][/m]
	[m3][*][ex][lang id=1033]a mile / seven yards long[/lang] — длиной в одну милю, семь ярдов[/ex][/*][/m]
	[m3][*][ex][lang id=1033]How long is your nose?[/lang] — Какой длины твой нос?[/ex][/*][/m]
	[m1]2)[/m]
	[m2]а) [trn]долгий, длительный, существующий давно; продолжительный; затяжной[/trn][/m]
	[m3][*][ex][lang id=1033]long vacation[/lang] — летние каникулы [i][com](в университетах и судах Великобритании)[/com][/ex][/i][/*][/m]
	[m3][*][ex][lang id=1033]a long(-lasting) relationship / friendship / love[/lang] — длительные отношения, старинная дружба, любовь надолго[/ex][/*][/m]
	[m3][*][ex][lang id=1033]an illness of long standing[/lang] — застарелая болезнь[/ex][/*][/m]
	[m3][*][ex][lang id=1033]long cold winter[/lang] — долгая холодная зима[/ex][/*][/m]
	[m3][*][ex][lang id=1033]long custom / tradition[/lang] — старинный обычай, давняя традиция[/ex][/*][/m]
	[m3][*][ex][lang id=1033]long words[/lang] — длинная, долгая речь[/ex][/*][/m]
	[m3][*][ex][lang id=1033]long memory[/lang] — долгая, хорошая память[/ex][/*][/m]
	[m3][*][ex][lang id=1033]for a long time[/lang] — очень долго[/ex][/*][/m]
	[m3][*][ex][lang id=1033]a long time ago[/lang] — очень давно[/ex][/*][/m]
	[m3][*][ex][lang id=1033]in the long term[/lang] — долгосрочный; перспективный[/ex][/*][/m]
	[m3][*][ex][lang id=1033]long service[/lang] — [p]воен.[/p] сверхсрочная служба[/ex][/*][/m]
	[m3][*][ex][lang id=1033]Long time no see![/lang] — [p]амер.[/p]; [p]шутл.[/p] Давно не виделись! [i][com](намеренно коверкая язык)[/com][/ex][/i][/*][/m]
	[m3][*][ex][lang id=1033]We took a long farewell.[/lang] — Мы долго прощались.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]She gave him a long look / stare.[/lang] — Она пристально посмотрела на него.[/ex][/*][/m]
	[m2]б) [trn]обладающий определённой протяжённостью, длящийся столько-то[/trn][/m]
	[m3][*][ex][lang id=1033]a (whole) life long[/lang] — длиной в (целую) жизнь; всю жизнь[/ex][/*][/m]
	[m3][*][ex][lang id=1033]an hour / three hours long[/lang] — часовой (продолжительностью в один час), трёхчасовой[/ex][/*][/m]
	[m3][*][ex][lang id=1033](two days, a week) at (the) longest[/lang] — самое большее (два дня, неделю)[/ex][/*][/m]
	[m3][*][ex][lang id=1033]How long does it take you to get there?[/lang] — Сколько времени тебе нужно, чтобы добраться туда?[/ex][/*][/m]
	[m1]3) [trn]долгий, медленный; неспешный, медлительный[/trn][/m]
	[m2][*][ex][lang id=1033]a long count by the referee[/lang] — (намеренно) медленный отсчёт времени судьёй [i][com](в спорте)[/com][/ex][/i][/*][/m]
	[m2][*][ex][lang id=1033]to be long about smth., to be long doing smth.[/lang] — копошиться, копаться [i][com](делая что-л.)[/com][/i]; возиться, канителиться [i][com](с чем-л.)[/com][/ex][/i][/*][/m]
	[m2][*][ex][lang id=1033]How long he is![/lang] — Что он так долго?![/ex][/*][/m]
	[m1]4)[/m]
	[m2]а) [trn]многочисленный, большой; обширный [i][com](состоящий из многих пунктов, насчитывающий много объектов)[/com][/trn][/i][/m]
	[m3][*][ex][lang id=1033]long list[/lang] — огромный, длинный список[/ex][/*][/m]
	[m3][*][ex][lang id=1033](a book) 300 pages long[/lang] — (книга) в триста страниц[/ex][/*][/m]
	[m3][*][ex][lang id=1033]long family[/lang] — большая, многодетная семья[/ex][/*][/m]
	[m2]б) [trn]огромный, избыточный, непомерно высокий[/trn][/m]
	[m3][*][ex][lang id=1033]long odds[/lang] — [p]карт.[/p] высокие ставки[/ex][/*][/m]
	[m3][*][ex][lang id=1033]long bill[/lang] — раздутый счёт[/ex][/*][/m]
	[m3][*][ex][lang id=1033]long prices[/lang] — непомерные, бешеные цены[/ex][/*][/m]
	[m3][*][ex][lang id=1033]The guy's a long purse![/lang] — У него денег до чёрта![/ex][/*][/m]
	[m3][*][b]Syn:[/b][/*][/m]
	[m3][*][ref]high[/ref], [ref]large[/ref][/*][/m]
	[m1]5) [trn]длинный, далёкий [i][com](далеко направленный)[/com][/trn][/i][/m]
	[m2][*][ex][lang id=1033]a long left jab[/lang] — длинный удар левой [i][com](в боксе)[/com][/ex][/i][/*][/m]
	[m2][*][ex][lang id=1033]to hit the long ball[/lang] — выбить мяч далеко, сильно ударить [i][com](в футболе)[/com][/ex][/i][/*][/m]
	[m2][*][ex][lang id=1033]at long weapon[/lang] — [p]воен.[/p] на расстоянии[/ex][/*][/m]
	[m2][*][ex][lang id=1033]long train[/lang] — поезд дальнего следования [i][com](от[/com][/i] long distance train)[/ex][/*][/m]
	[m1]6) [p][trn]лингв.[/trn][/p][/m]
	[m2]а) [trn]долгий [i][com](гласный)[/com][/i]; слоговой [i][com](об элементе дифтонга)[/com][/trn][/i][/m]
	[m2]б) [trn]ударный[/trn][/m]
	[m1]7)[/m]
	[m2]а) [trn]отдалённый, отложенный на будущее[/trn][/m]
	[m3][*][ex][lang id=1033]long date[/lang] — отдалённый срок[/ex][/*][/m]
	[m3][*][ex][lang id=1033]long thoughts[/lang] — мысли о будущем[/ex][/*][/m]
	[m3][*][ex][lang id=1033]long guess[/lang] — долгосрочный прогноз, ожидание на будущее[/ex][/*][/m]
	[m2]б) [p][trn]фин.[/p] долгосрочный[/trn][/m]
	[m3][*][ex][lang id=1033]a long note / bill / lease[/lang] — долгосрочный вексель, аренда[/ex][/*][/m]
	[m1]8) [i][trn][com](long on)[/com][/trn][/i][/m]
	[m2]а) [trn]отличающийся [i][com](какой-л. чертой)[/com][/trn][/i][/m]
	[m3][*][ex][lang id=1033]to be long on common sense[/lang] — быть весьма здравомыслящим[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to be long on hope[/lang] — не переставать надеяться[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to be long on patience[/lang] — очень долго терпеть, уметь долго ждать[/ex][/*][/m]
	[m2]б) [p]амер.[/p][c];[/c] [p]разг.[/p] [trn]богатый [i][com](чем-л.)[/com][/i], сильный в [i][com](чём-л.)[/com][/trn][/i][/m]
	[m3][*][ex][lang id=1033]He's long on good ideas.[/lang] — Он полон хороших идей.[/ex][/*][/m]
	[m1]9) [trn]целый, добрый[/trn][/m]
	[m2][*][ex][lang id=1033]long mile[/lang] — целая миля, не меньше мили[/ex][/*][/m]
	[m2][*][ex][lang id=1033]to be waiting for a long hour[/lang] — ждать битый час[/ex][/*][/m]
	[m1]10) [trn]продолговатый, удлинённый[/trn][/m]
	[m1]11) [p][trn]фин.[/p] играющий на повышение[/trn][/m]
	[m2][*][ex][lang id=1033]They are now long on wheat.[/lang] — Сейчас они играют на повышение цен на пшеницу.[/ex][/*][/m]
	[m1][*]•[/*][/m]
	[m1][*]- [ref]long nine[/ref][/*][/m]
	[m1][*]- [ref]Long Tom[/ref][/*][/m]
	[m1][*]- [ref]Long Parliament[/ref][/*][/m]
	[m1][*]- [ref]long suit[/ref][/*][/m]
	[m1][*]- [ref]long in the tooth[/ref][/*][/m]
	[m1][*][ex][lang id=1033]long shillings[/lang] — хороший заработок[/ex][/*][/m]
	[m1][*][ex][lang id=1033]long ears[/lang] — глупость, наивность[/ex][/*][/m]
	[m1][*][ex][lang id=1033]long head[/lang] — ум, башковитость; предусмотрительность[/ex][/*][/m]
	[m1][*][ex][lang id=1033]to make a long nose[/lang] — показать "нос"[/ex][/*][/m]
	[m1][*][ex][lang id=1033]to have a long tongue[/lang] — много болтать[/ex][/*][/m]
	[m1][*][ex][lang id=1033]to make / pull a long face[/lang] — помрачнеть[/ex][/*][/m]
	[m1][*][ex][lang id=1033]to get a long start over smb.[/lang] — значительно опередить кого-л.[/ex][/*][/m]
	[m1][*][b]Gram:[/b][/*][/m]
	[m1][*]-[ref dict="LingvoGrammar (En-Ru)"]long[/ref][/*][/m]
	[m1][b]2.[/b] [p]нареч.[/p][/m]
	[m1]1)[/m]
	[m2]а) [trn]долго, длительно; в течение долгого времени[/trn][/m]
	[m3][*][ex][lang id=1033]long a popular hangout[/lang] — долгое время популярное заведение[/ex][/*][/m]
	[m3][*][ex][lang id=1033]It won't be long.[/lang] — Это ненадолго.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]Stay for as long as you like.[/lang] — Оставайтесь столько, сколько вам будет угодно.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]Wait a while longer.[/lang] — Подождите ещё немного.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I shall not wait (any) longer.[/lang] — Не буду больше ждать.[/ex][/*][/m]
	[m2]б) [trn]до определённого времени[/trn][/m]
	[m3][*][ex][lang id=1033]She didn't stay longer than midnight.[/lang] — Она осталась только до полуночи.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]It is no longer possible.[/lang] — Это больше невозможно.[/ex][/*][/m]
	[m1]2) [trn]далеко, на далёкое расстояние[/trn][/m]
	[m2][*][ex][lang id=1033]I didn't travel that long.[/lang] — Я так далеко не ездил.[/ex][/*][/m]
	[m2][*][ex][lang id=1033]He threw the ball long.[/lang] — Он бросил мяч далеко.[/ex][/*][/m]
	[m2][*][b]Syn:[/b][/*][/m]
	[m2][*][ref]far[/ref][/*][/m]
	[m1]3)[/m]
	[m2]а) [trn]давно, задолго до[/trn][/m]
	[m3][*][ex][lang id=1033]long ago / since[/lang] — давным-давно, уже очень давно[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to be past long[/lang] — случаться давно[/ex][/*][/m]
	[m3][*][ex][lang id=1033]long past[/lang] — давнопрошедший; давний, далёкий[/ex][/*][/m]
	[m3][*][ex][lang id=1033]long before you were born[/lang] — задолго до твоего появления на свет[/ex][/*][/m]
	[m3][*][ex][lang id=1033]She was excited long before the big day.[/lang] — Она была вся в нервном напряжении ещё задолго до этого события.[/ex][/*][/m]
	[m2]б) [trn]потом; долгое время спустя[/trn][/m]
	[m3][*][ex][lang id=1033]long after midnight[/lang] — далеко за полночь[/ex][/*][/m]
	[m1]4) [trn]полностью, целиком[/trn][/m]
	[m2][*][ex][lang id=1033]all day / night long[/lang] — целый день, всю ночь (напролёт)[/ex][/*][/m]
	[m2][*][ex][lang id=1033]all smb.'s life long[/lang] — всю свою жизнь; в течение всей своей жизни[/ex][/*][/m]
	[m1]5) [p][trn]фин.[/p] на повышение[/trn][/m]
	[m2][*][ex][lang id=1033]to go long 100 shares[/lang] — купить 100 акций в расчёте на повышение[/ex][/*][/m]
	[m1][*]•[/*][/m]
	[m1][*][ex][lang id=1033]you may do smth. long enough[/lang] — хоть в лепёшку разбейся[/ex][/*][/m]
	[m1]- [ref]as long as[/ref][/m]
	[m1]- [ref]long live[/ref][/m]
	[m1]- [ref]so long[/ref][/m]
	[m1][b]3.[/b] [p]сущ.[/p][/m]
	[m1]1) [trn]долгое время; долгий срок, долгий период времени[/trn][/m]
	[m2][*][ex][lang id=1033]before long[/lang] — скоро; вскоре, в ближайшем времени[/ex][/*][/m]
	[m2][*][ex][lang id=1033]for long[/lang] — надолго, на долгое время[/ex][/*][/m]
	[m2][*][ex][lang id=1033]It can take long.[/lang] — Это может занять много времени.[/ex][/*][/m]
	[m2][*][ex][lang id=1033]It didn't take him long to come.[/lang] — Его не пришлось долго ждать.[/ex][/*][/m]
	[m1]2) [p][trn]лингв.[/p] долгий гласный; слоговой гласный дифтонга[/trn][/m]
	[m1]3) [i][trn][com](the long)[/com][/i] летние каникулы [i][com](в университетах и судах Великобритании)[/com][/trn][/i][/m]
	[m2][*][b]Syn:[/b][/*][/m]
	[m2][*]long vacation[/*][/m]
	[m1]4) [p][trn]фин.[/p] маклер, спекулянт, играющий на повышение[/trn][/m]
	[m1]5) [i][trn][com](longs)[/com][/trn][/i][/m]
	[m2]а) [trn]брюки, длинные штаны [i][com](в противопоставление[/com][/i] [ref]shorts[/ref])[/trn][/m]
	[m2]б) [trn]большие размеры мужской одежды[/trn][/m]
	[m1][*]•[/*][/m]
	[m1]- [ref]long and the short of it[/ref][/m]
	[m1]- [ref]long and short of it[/ref][/m]
	[b]II[/b] [p]гл.[/p]
	[m1][trn]очень хотеть, страстно желать [i][com](чего-л.)[/com][/i], испытывать потребность [i][com](в чём-л.)[/com][/i], стремиться [i][com](к чему-л.)[/com][/trn][/i][/m]
	[m2][*][ex][lang id=1033]I long for you.[/lang] — Ты мне очень нужен, я не могу без тебя.[/ex][/*][/m]
	[m2][*][ex][lang id=1033]After she left me I was longing for a change in my life.[/lang] — После того, как она меня покинула, мне очень хотелось радикально изменить свою жизнь.[/ex][/*][/m]
	[m2][*][ex][lang id=1033]He was longing for a shower.[/lang] — Он не мог дождаться момента, когда сможет принять душ.[/ex][/*][/m]
	[m2][*][ex][lang id=1033]They long for peace but are driven to war.[/lang] — Они стремятся к миру, а их заставляют воевать.[/ex][/*][/m]
	[m2][*][ex][lang id=1033]I'm longing for a smoke.[/lang] — До смерти хочется курить.[/ex][/*][/m]
	[m2][*][b]Syn:[/b][/*][/m]
	[m2][*][ref]yearn[/ref], [ref]wish[/ref], [ref]desire[/ref], to be eager[/*][/m]
